-- MESS KARYAWAN / PT KPS — versi sederhana
-- Jalankan seluruh file ini di SQL Editor Supabase (PostgreSQL 15+).
-- Semua objek aplikasi menggunakan awalan mess_ agar tidak menimpa web lama.
-- Skrip dapat dijalankan ulang; tidak menghapus data yang sudah tersimpan.
begin;

create table if not exists public.mess_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  nama text not null default '',
  role text not null default 'pengguna' check (role in ('pengguna','admin','super_admin')),
  avatar_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.mess_rooms (
  id bigint generated by default as identity primary key,
  lokasi_hunian text not null check (length(btrim(lokasi_hunian)) between 1 and 160),
  block text not null check (length(btrim(block)) between 1 and 30),
  no_kamar text not null check (length(btrim(no_kamar)) between 1 and 30),
  floor text,
  gender text check (gender in ('L','P')),
  golongan integer check (golongan between 1 and 30),
  fasilitas text check (fasilitas in ('CR','NR')),
  jumlah_bed integer not null default 4 check (jumlah_bed between 1 and 100),
  rusak boolean not null default false,
  catatan text,
  kebersihan jsonb not null default '{"items":{}}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.mess_code(p_text text) returns text
language sql immutable set search_path = ''
as $$
 select case when btrim(p_text) ~ '^[0-9]+$'
   then coalesce(nullif(ltrim(btrim(p_text),'0'),''),'0')
   else lower(btrim(p_text)) end
$$;
create unique index if not exists mess_room_address
 on public.mess_rooms(lower(btrim(lokasi_hunian)),public.mess_code(block),public.mess_code(no_kamar));

create table if not exists public.mess_assets (
  id bigint generated by default as identity primary key,
  nama text not null check (length(btrim(nama)) between 1 and 100),
  harga numeric(15,0) not null default 0 check (harga >= 0),
  urutan integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.mess_tools (
  id bigint generated by default as identity primary key,
  nama text not null check (length(btrim(nama)) between 1 and 100),
  urutan integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.mess_employees (
  nik text primary key check (length(btrim(nik)) between 1 and 80),
  nama text not null check (length(btrim(nama)) between 1 and 200),
  gender text check (gender in ('L','P')),
  department text, jabatan text, gol text,
  fasilitas text check (fasilitas in ('CR','NR')),
  perusahaan text, point_of_hire text,
  tgl_masuk_kerja date, tgl_masuk_mess date,
  status text not null default 'aktif' check (status in ('aktif','resign')),
  kamar_id bigint references public.mess_rooms(id) on delete restrict,
  no_bed integer check (no_bed between 1 and 100),
  perlengkapan jsonb not null default '{}'::jsonb,
  link_bukti text,
  tgl_resign date, alasan_resign text, resign_oleh text,
  aset_kembali jsonb not null default '[]'::jsonb,
  aset_snapshot jsonb not null default '[]'::jsonb,
  potongan numeric(15,0) not null default 0 check (potongan >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mess_employee_bed_pair check ((kamar_id is null) = (no_bed is null)),
  constraint mess_resign_no_bed check (status <> 'resign' or kamar_id is null)
);
create unique index if not exists mess_one_person_per_bed
 on public.mess_employees(kamar_id,no_bed) where status='aktif' and kamar_id is not null;
create index if not exists mess_employee_name on public.mess_employees(lower(nama));
create index if not exists mess_employee_status on public.mess_employees(status);

create table if not exists public.mess_moves (
  id bigint generated by default as identity primary key,
  nik text not null references public.mess_employees(nik) on update cascade on delete cascade,
  tipe text not null check (tipe in ('penempatan','pindah','keluar')),
  dari_kamar_id bigint references public.mess_rooms(id) on delete set null,
  ke_kamar_id bigint references public.mess_rooms(id) on delete set null,
  dari_label text, ke_label text,
  dari_no_bed integer, ke_no_bed integer,
  oleh_email text not null,
  waktu timestamptz not null default now(),
  diantar boolean not null default false,
  diantar_oleh text, diantar_pada timestamptz,
  dibatalkan boolean not null default false
);
create index if not exists mess_moves_time on public.mess_moves(waktu desc,id desc);
create index if not exists mess_moves_employee on public.mess_moves(nik);
create index if not exists mess_moves_waiting on public.mess_moves(waktu desc)
 where not diantar and not dibatalkan;

create table if not exists public.mess_deletions (
  id bigint generated by default as identity primary key,
  jenis text not null, ref text not null, nama text not null,
  detail text, data_lengkap jsonb not null,
  oleh_email text not null, waktu timestamptz not null default now()
);

-- Nilai role dibaca langsung dari tabel terlindungi; bukan dari input browser.
create or replace function public.mess_level() returns integer
language sql stable security definer set search_path = ''
as $$
 select coalesce((select case role when 'super_admin' then 2 when 'admin' then 1 else 0 end
   from public.mess_profiles where user_id=auth.uid()),0)
$$;
create or replace function public.mess_require(p_level integer) returns void
language plpgsql security definer set search_path = ''
as $$
begin
 if auth.uid() is null then raise exception 'Silakan masuk terlebih dahulu.'; end if;
 if public.mess_level()<p_level then raise exception 'Akun Anda tidak memiliki akses untuk tindakan ini.'; end if;
end
$$;
create or replace function public.mess_actor() returns text
language sql stable security definer set search_path = ''
as $$ select coalesce((select email from auth.users where id=auth.uid()),'') $$;

create or replace function public.mess_profile() returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare v_email text; v_name text; v_profile public.mess_profiles;
begin
 perform public.mess_require(0);
 select email,coalesce(raw_user_meta_data->>'nama','') into v_email,v_name
 from auth.users where id=auth.uid();
 insert into public.mess_profiles(user_id,email,nama)
 values(auth.uid(),v_email,v_name)
 on conflict(user_id) do update set email=excluded.email;
 select * into v_profile from public.mess_profiles where user_id=auth.uid();
 return to_jsonb(v_profile);
end
$$;

create or replace function public.mess_edit_profile(p_nama text,p_avatar_path text) returns jsonb
language plpgsql security definer set search_path = ''
as $$
begin
 perform public.mess_require(0);
 if length(coalesce(p_nama,''))>200 then raise exception 'Nama terlalu panjang.'; end if;
 if p_avatar_path is not null and
   (split_part(p_avatar_path,'/',1)<>auth.uid()::text or length(p_avatar_path)>250) then
   raise exception 'Lokasi foto tidak sesuai dengan akun.'; end if;
 perform public.mess_profile();
 update public.mess_profiles set nama=btrim(coalesce(p_nama,'')),avatar_path=p_avatar_path
 where user_id=auth.uid();
 return public.mess_profile();
end
$$;

create or replace function public.mess_set_role(p_email text,p_role text) returns void
language plpgsql security definer set search_path = ''
as $$
declare v_uid uuid; v_old_role text;
begin
 perform public.mess_require(1);
 if p_role is null or p_role not in ('pengguna','admin','super_admin') then raise exception 'Role tidak valid.'; end if;
 -- Menserialkan perubahan role untuk melindungi administrator terakhir.
 perform pg_catalog.pg_advisory_xact_lock(49172,1);
 select id into v_uid from auth.users where lower(email)=lower(btrim(p_email));
 if v_uid is null then raise exception 'Email belum terdaftar di Authentication Supabase.'; end if;
 if v_uid=auth.uid() then raise exception 'Role akun sendiri tidak dapat diubah dari halaman ini.'; end if;
 select role into v_old_role from public.mess_profiles where user_id=v_uid for update;
 if public.mess_level()<2 and (p_role='super_admin' or v_old_role='super_admin') then
   raise exception 'Hanya Administrator yang dapat mengubah akses Administrator.'; end if;
 insert into public.mess_profiles(user_id,email,role)
 values(v_uid,lower(btrim(p_email)),p_role)
 on conflict(user_id) do update set role=excluded.role,email=excluded.email;
end
$$;

create or replace function public.mess_save_room(p_id bigint,p_data jsonb) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare v_room public.mess_rooms; v_gender text; v_beds integer; v_loc text; v_block text; v_no text;
begin
 perform public.mess_require(case when p_id is null then 2 else 1 end);
 v_loc:=btrim(coalesce(p_data->>'lokasi_hunian',''));
 v_block:=btrim(coalesce(p_data->>'block','')); v_no:=btrim(coalesce(p_data->>'no_kamar',''));
 v_gender:=nullif(p_data->>'gender',''); v_beds:=(p_data->>'jumlah_bed')::integer;
 if v_loc='' or v_block='' or v_no='' then raise exception 'Lokasi, blok, dan nomor kamar wajib diisi.'; end if;
 if v_beds is null or v_beds<1 or v_beds>100 then raise exception 'Jumlah bed harus 1–100.'; end if;
 if p_id is not null then
   select * into v_room from public.mess_rooms where id=p_id for update;
   if not found then raise exception 'Kamar tidak ditemukan.'; end if;
   if nullif(p_data->>'expected_updated_at','') is not null
      and (p_data->>'expected_updated_at')::timestamptz <> v_room.updated_at then
     raise exception 'Data kamar sudah diubah oleh akun lain. Tutup formulir, perbarui data, lalu edit kembali.';
   end if;
   if exists(select 1 from public.mess_employees where kamar_id=p_id and no_bed>v_beds) then
     raise exception 'Jumlah bed tidak boleh lebih kecil dari nomor bed penghuni yang masih aktif.'; end if;
   if exists(select 1 from public.mess_employees where kamar_id=p_id and gender is distinct from v_gender) then
     raise exception 'Gender kamar harus sesuai dengan penghuni yang masih aktif.'; end if;
   update public.mess_rooms set lokasi_hunian=v_loc,block=v_block,no_kamar=v_no,
     floor=nullif(btrim(p_data->>'floor'),''),gender=v_gender,
     golongan=nullif(p_data->>'golongan','')::integer,
     fasilitas=nullif(p_data->>'fasilitas',''),jumlah_bed=v_beds,
     rusak=coalesce((p_data->>'rusak')::boolean,false),catatan=nullif(btrim(p_data->>'catatan'),''),
     updated_at=now() where id=p_id returning * into v_room;
 else
   insert into public.mess_rooms(lokasi_hunian,block,no_kamar,floor,gender,golongan,fasilitas,jumlah_bed,rusak,catatan)
   values(v_loc,v_block,v_no,nullif(btrim(p_data->>'floor'),''),v_gender,
     nullif(p_data->>'golongan','')::integer,nullif(p_data->>'fasilitas',''),v_beds,
     coalesce((p_data->>'rusak')::boolean,false),nullif(btrim(p_data->>'catatan'),''))
   returning * into v_room;
 end if;
 return to_jsonb(v_room);
exception when unique_violation then raise exception 'Kamar dengan lokasi, blok, dan nomor ini sudah terdaftar.';
end
$$;

create or replace function public.mess_save_employee(p_old_nik text,p_data jsonb) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
 v_old public.mess_employees; v_emp public.mess_employees; v_room public.mess_rooms;
 v_nik text; v_nama text; v_gender text; v_status text; v_pl jsonb:='{}';
 v_key text; v_return jsonb:='[]'; v_snapshot jsonb:='[]'; v_cut numeric:=0;
 v_exit date; v_actor text; v_label text;
begin
 perform public.mess_require(1);
 v_actor:=public.mess_actor();
 v_nik:=btrim(coalesce(p_data->>'nik','')); v_nama:=btrim(coalesce(p_data->>'nama',''));
 v_gender:=nullif(p_data->>'gender',''); v_status:=coalesce(p_data->>'status','aktif');
 if v_nik='' or v_nama='' then raise exception 'NIK dan nama wajib diisi.'; end if;
 if v_status not in ('aktif','resign') then raise exception 'Status karyawan tidak valid.'; end if;
 foreach v_key in array array['selimut','bantal_kepala','bantal_guling','sarung_bantal','seprai'] loop
   v_pl:=v_pl||jsonb_build_object(v_key,coalesce((p_data->'perlengkapan'->>v_key)::boolean,false));
 end loop;
 if coalesce(p_data->>'link_bukti','')<>'' and (p_data->>'link_bukti') !~ '^https?://' then
   raise exception 'Link bukti harus dimulai dengan https:// atau http://.'; end if;
 if p_old_nik is not null then
   select * into v_old from public.mess_employees where nik=p_old_nik for update;
   if not found then raise exception 'Karyawan tidak ditemukan. Muat ulang daftar.'; end if;
   if nullif(p_data->>'expected_updated_at','') is not null
      and (p_data->>'expected_updated_at')::timestamptz <> v_old.updated_at then
     raise exception 'Data karyawan sudah diubah oleh akun lain. Tutup formulir, perbarui data, lalu edit kembali.';
   end if;
 end if;
 if v_old.kamar_id is not null then
   select * into v_room from public.mess_rooms where id=v_old.kamar_id for update;
   if v_status='aktif' and v_gender is distinct from v_room.gender then
     raise exception 'Gender karyawan harus sesuai kamar. Pindahkan penempatannya terlebih dahulu.'; end if;
 end if;
 if v_status='resign' then
   v_exit:=coalesce(nullif(p_data->>'tgl_resign','')::date,(now() at time zone 'Asia/Jayapura')::date);
   v_return:=coalesce(p_data->'aset_kembali','[]'::jsonb);
   if jsonb_typeof(v_return)<>'array' then raise exception 'Daftar aset tidak valid.'; end if;
   -- Pertahankan harga saat resign; perubahan harga master tidak mengubah riwayat.
   if v_old.status='resign' then v_snapshot:=v_old.aset_snapshot;
   else
     select coalesce(jsonb_agg(jsonb_build_object('id',id,'nama',nama,'harga',harga) order by urutan,id),'[]')
       into v_snapshot from public.mess_assets;
   end if;
   if exists(select 1 from jsonb_array_elements(v_return) x where jsonb_typeof(x)<>'number'
      or not exists(select 1 from jsonb_array_elements(v_snapshot) s where s->'id'=x)) then
     raise exception 'Daftar aset pengembalian tidak sesuai.'; end if;
   select coalesce(sum((s->>'harga')::numeric),0) into v_cut
   from jsonb_array_elements(v_snapshot) s where not (v_return @> jsonb_build_array(s->'id'));
 end if;
 if p_old_nik is null then
   insert into public.mess_employees(nik,nama,gender,department,jabatan,gol,fasilitas,perusahaan,
     point_of_hire,tgl_masuk_kerja,tgl_masuk_mess,status,perlengkapan,link_bukti,
     tgl_resign,alasan_resign,resign_oleh,aset_kembali,aset_snapshot,potongan)
   values(v_nik,v_nama,v_gender,nullif(btrim(p_data->>'department'),''),nullif(btrim(p_data->>'jabatan'),''),
     nullif(btrim(p_data->>'gol'),''),nullif(p_data->>'fasilitas',''),nullif(btrim(p_data->>'perusahaan'),''),
     nullif(btrim(p_data->>'point_of_hire'),''),nullif(p_data->>'tgl_masuk_kerja','')::date,
     nullif(p_data->>'tgl_masuk_mess','')::date,v_status,v_pl,nullif(btrim(p_data->>'link_bukti'),''),
     v_exit,case when v_status='resign' then nullif(btrim(p_data->>'alasan_resign'),'') end,
     case when v_status='resign' then v_actor end,v_return,v_snapshot,v_cut) returning * into v_emp;
 else
   update public.mess_employees set nik=v_nik,nama=v_nama,gender=v_gender,
     department=nullif(btrim(p_data->>'department'),''),jabatan=nullif(btrim(p_data->>'jabatan'),''),
     gol=nullif(btrim(p_data->>'gol'),''),fasilitas=nullif(p_data->>'fasilitas',''),
     perusahaan=nullif(btrim(p_data->>'perusahaan'),''),point_of_hire=nullif(btrim(p_data->>'point_of_hire'),''),
     tgl_masuk_kerja=nullif(p_data->>'tgl_masuk_kerja','')::date,
     tgl_masuk_mess=nullif(p_data->>'tgl_masuk_mess','')::date,status=v_status,perlengkapan=v_pl,
     link_bukti=nullif(btrim(p_data->>'link_bukti'),''),tgl_resign=v_exit,
     alasan_resign=case when v_status='resign' then nullif(btrim(p_data->>'alasan_resign'),'') end,
     resign_oleh=case when v_status='resign' then coalesce(v_old.resign_oleh,v_actor) end,
     aset_kembali=v_return,aset_snapshot=v_snapshot,potongan=v_cut,
     kamar_id=case when v_status='resign' then null else kamar_id end,
     no_bed=case when v_status='resign' then null else no_bed end,updated_at=now()
   where nik=p_old_nik returning * into v_emp;
   if v_status='resign' and v_old.status='aktif' then
     update public.mess_moves set dibatalkan=true where nik=v_nik and not diantar;
     if v_old.kamar_id is not null then
       v_label:=v_room.lokasi_hunian||' · Blok '||v_room.block||' · Kamar '||v_room.no_kamar;
       insert into public.mess_moves(nik,tipe,dari_kamar_id,dari_label,dari_no_bed,oleh_email,diantar)
       values(v_nik,'keluar',v_old.kamar_id,v_label,v_old.no_bed,v_actor,true);
     end if;
   end if;
 end if;
 return to_jsonb(v_emp);
exception when unique_violation then raise exception 'NIK ini sudah terdaftar.';
end
$$;

create or replace function public.mess_move_employee(p_nik text,p_kamar_id bigint,p_no_bed integer) returns void
language plpgsql security definer set search_path = ''
as $$
declare v_emp public.mess_employees; v_room public.mess_rooms; v_from text; v_to text;
begin
 perform public.mess_require(1);
 select * into v_emp from public.mess_employees where nik=p_nik for update;
 if not found then raise exception 'Karyawan tidak ditemukan.'; end if;
 if v_emp.status<>'aktif' then raise exception 'Karyawan resign tidak dapat ditempatkan.'; end if;
 select * into v_room from public.mess_rooms where id=p_kamar_id for update;
 if not found then raise exception 'Kamar tidak ditemukan.'; end if;
 if v_emp.gender is null or v_room.gender is null or v_emp.gender<>v_room.gender then
   raise exception 'Gender karyawan dan kamar harus diisi dan sama.'; end if;
 if p_no_bed is null or p_no_bed<1 or p_no_bed>v_room.jumlah_bed then
   raise exception 'Nomor bed di luar kapasitas kamar.'; end if;
 if v_emp.kamar_id=p_kamar_id and v_emp.no_bed=p_no_bed then raise exception 'Karyawan sudah berada di bed ini.'; end if;
 if exists(select 1 from public.mess_employees where kamar_id=p_kamar_id and no_bed=p_no_bed and status='aktif') then
   raise exception 'Bed sudah terisi. Pilih bed yang lain.'; end if;
 select lokasi_hunian||' · Blok '||block||' · Kamar '||no_kamar into v_from
 from public.mess_rooms where id=v_emp.kamar_id;
 v_to:=v_room.lokasi_hunian||' · Blok '||v_room.block||' · Kamar '||v_room.no_kamar;
 update public.mess_moves set dibatalkan=true where nik=p_nik and not diantar;
 update public.mess_employees set kamar_id=p_kamar_id,no_bed=p_no_bed,updated_at=now() where nik=p_nik;
 insert into public.mess_moves(nik,tipe,dari_kamar_id,ke_kamar_id,dari_label,ke_label,
   dari_no_bed,ke_no_bed,oleh_email)
 values(p_nik,case when v_emp.kamar_id is null then 'penempatan' else 'pindah' end,
   v_emp.kamar_id,p_kamar_id,v_from,v_to,v_emp.no_bed,p_no_bed,public.mess_actor());
exception when unique_violation then raise exception 'Bed baru saja terisi oleh akun lain. Pilih bed yang lain.';
end
$$;

create or replace function public.mess_mark_delivered(p_id bigint) returns void
language plpgsql security definer set search_path = ''
as $$
begin
 perform public.mess_require(1);
 update public.mess_moves set diantar=true,diantar_oleh=public.mess_actor(),diantar_pada=now()
 where id=p_id and not dibatalkan and not diantar;
 if not found then raise exception 'Pindahan sudah diproses atau dibatalkan. Muat ulang daftar.'; end if;
end
$$;

create or replace function public.mess_save_cleaning(p_id bigint,p_data jsonb) returns void
language plpgsql security definer set search_path = ''
as $$
declare v_tool record; v_item jsonb; v_items jsonb:='{}'; v_date date; v_on boolean; v_updated timestamptz;
begin
 perform public.mess_require(2);
 if jsonb_typeof(p_data->'items') is distinct from 'object' then
   raise exception 'Daftar pengambilan alat tidak valid.';
 end if;
 select updated_at into v_updated from public.mess_rooms where id=p_id for update;
 if not found then raise exception 'Kamar tidak ditemukan.'; end if;
 if nullif(p_data->>'expected_updated_at','') is not null
    and (p_data->>'expected_updated_at')::timestamptz <> v_updated then
   raise exception 'Data kamar sudah berubah. Tutup formulir dan perbarui data terlebih dahulu.';
 end if;
 for v_tool in select id from public.mess_tools order by urutan,id loop
   v_item:=p_data->'items'->v_tool.id::text;
   v_on:=coalesce((v_item->>'ambil')::boolean,false);
   v_date:=nullif(v_item->>'tgl','')::date;
   v_items:=v_items||jsonb_build_object(v_tool.id::text,case when v_on
     then jsonb_build_object('ambil',true,'tgl',v_date,'nama',nullif(btrim(v_item->>'nama'),''),
       'nik',nullif(btrim(v_item->>'nik'),''))
     else jsonb_build_object('ambil',false) end);
 end loop;
 update public.mess_rooms set kebersihan=jsonb_build_object('items',v_items),updated_at=now() where id=p_id;
end
$$;

create or replace function public.mess_master(
 p_kind text,p_id bigint,p_nama text,p_harga numeric,p_urutan integer,p_delete boolean
) returns void
language plpgsql security definer set search_path = ''
as $$
begin
 if p_kind is null or p_kind not in ('aset','alat') then raise exception 'Jenis master tidak valid.'; end if;
 perform public.mess_require(case when p_kind='alat' then 2 else 1 end);
 if coalesce(p_delete,false) then
   if p_id is null then raise exception 'Item tidak ditemukan.'; end if;
   if p_kind='aset' then delete from public.mess_assets where id=p_id;
   else delete from public.mess_tools where id=p_id; end if;
   return;
 end if;
 if btrim(coalesce(p_nama,''))='' then raise exception 'Nama item wajib diisi.'; end if;
 if coalesce(p_harga,0)<0 then raise exception 'Harga tidak boleh negatif.'; end if;
 if p_kind='aset' then
   if p_id is null then insert into public.mess_assets(nama,harga,urutan) values(btrim(p_nama),coalesce(p_harga,0),coalesce(p_urutan,0));
   else update public.mess_assets set nama=btrim(p_nama),harga=coalesce(p_harga,0),urutan=coalesce(p_urutan,0) where id=p_id; end if;
 else
   if p_id is null then insert into public.mess_tools(nama,urutan) values(btrim(p_nama),coalesce(p_urutan,0));
   else update public.mess_tools set nama=btrim(p_nama),urutan=coalesce(p_urutan,0) where id=p_id; end if;
 end if;
end
$$;

create or replace function public.mess_delete_employee(p_nik text) returns void
language plpgsql security definer set search_path = ''
as $$
declare v_emp public.mess_employees; v_snapshot jsonb;
begin
 perform public.mess_require(1);
 select * into v_emp from public.mess_employees where nik=p_nik for update;
 if not found then raise exception 'Karyawan tidak ditemukan.'; end if;
 select jsonb_build_object('karyawan',to_jsonb(v_emp),
   'kamar',(select to_jsonb(r) from public.mess_rooms r where r.id=v_emp.kamar_id),
   'riwayat',(select coalesce(jsonb_agg(to_jsonb(m) order by m.waktu),'[]') from public.mess_moves m where m.nik=p_nik))
 into v_snapshot;
 insert into public.mess_deletions(jenis,ref,nama,detail,data_lengkap,oleh_email)
 values('Karyawan',p_nik,v_emp.nama,'Data karyawan dan riwayat perpindahan dihapus.',v_snapshot,public.mess_actor());
 delete from public.mess_employees where nik=p_nik;
end
$$;

create or replace function public.mess_delete_room(p_id bigint) returns void
language plpgsql security definer set search_path = ''
as $$
declare v_room public.mess_rooms;
begin
 perform public.mess_require(2);
 select * into v_room from public.mess_rooms where id=p_id for update;
 if not found then raise exception 'Kamar tidak ditemukan.'; end if;
 if exists(select 1 from public.mess_employees where kamar_id=p_id) then
   raise exception 'Kamar masih berpenghuni dan tidak dapat dihapus.'; end if;
 insert into public.mess_deletions(jenis,ref,nama,detail,data_lengkap,oleh_email)
 values('Kamar',p_id::text,v_room.lokasi_hunian||' · Blok '||v_room.block||' · Kamar '||v_room.no_kamar,
   'Kamar kosong dihapus.',to_jsonb(v_room),public.mess_actor());
 delete from public.mess_rooms where id=p_id;
end
$$;

-- Semua query tampilan tunduk pada RLS (security_invoker, PostgreSQL 15+).
create or replace view public.mess_room_status with (security_invoker=true) as
 select r.*,coalesce(o.terisi,0)::integer as terisi,
   greatest(r.jumlah_bed-coalesce(o.terisi,0),0)::integer as sisa,
   case when coalesce(o.terisi,0)=0 then 'KOSONG'
        when coalesce(o.terisi,0)>=r.jumlah_bed then 'FULL' else 'TERISI' end as status_kamar
 from public.mess_rooms r
 left join (select kamar_id,count(*) as terisi from public.mess_employees
   where status='aktif' and kamar_id is not null group by kamar_id) o on o.kamar_id=r.id;

-- RLS: akun masuk dapat membaca operasional. Semua perubahan lewat RPC yang memeriksa role.
alter table public.mess_profiles enable row level security;
alter table public.mess_rooms enable row level security;
alter table public.mess_employees enable row level security;
alter table public.mess_assets enable row level security;
alter table public.mess_tools enable row level security;
alter table public.mess_moves enable row level security;
alter table public.mess_deletions enable row level security;
drop policy if exists mess_profile_read on public.mess_profiles;
create policy mess_profile_read on public.mess_profiles for select to authenticated
 using (user_id=(select auth.uid()) or (select public.mess_level())>=1);
drop policy if exists mess_room_read on public.mess_rooms;
create policy mess_room_read on public.mess_rooms for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists mess_employee_read on public.mess_employees;
create policy mess_employee_read on public.mess_employees for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists mess_asset_read on public.mess_assets;
create policy mess_asset_read on public.mess_assets for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists mess_tool_read on public.mess_tools;
create policy mess_tool_read on public.mess_tools for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists mess_move_read on public.mess_moves;
create policy mess_move_read on public.mess_moves for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists mess_deletion_read on public.mess_deletions;
create policy mess_deletion_read on public.mess_deletions for select to authenticated using ((select public.mess_level())>=1);
revoke all on public.mess_profiles,public.mess_rooms,public.mess_employees,public.mess_assets,
 public.mess_tools,public.mess_moves,public.mess_deletions,public.mess_room_status from anon,authenticated;
grant select on public.mess_profiles,public.mess_rooms,public.mess_employees,public.mess_assets,
 public.mess_tools,public.mess_moves,public.mess_deletions,public.mess_room_status to authenticated;

-- Hak eksekusi hanya untuk fungsi aplikasi yang memang dipanggil browser.
-- Berlaku hanya pada fungsi mess_; fungsi dan kebijakan milik web lama tidak disentuh.
do $$
declare r record;
begin
 for r in select p.oid::regprocedure as fn from pg_catalog.pg_proc p
 join pg_catalog.pg_namespace n on n.oid=p.pronamespace
 where n.nspname='public' and p.proname like 'mess\_%' escape '\' loop
   execute format('revoke all on function %s from public, anon, authenticated',r.fn);
 end loop;
end
$$;
grant execute on function public.mess_code(text),public.mess_level(),
 public.mess_profile(),public.mess_edit_profile(text,text),public.mess_set_role(text,text),
 public.mess_save_room(bigint,jsonb),public.mess_save_employee(text,jsonb),
 public.mess_move_employee(text,bigint,integer),public.mess_mark_delivered(bigint),
 public.mess_save_cleaning(bigint,jsonb),public.mess_master(text,bigint,text,numeric,integer,boolean),
 public.mess_delete_employee(text),public.mess_delete_room(bigint) to authenticated;

-- Foto profil privat, hanya pemilik yang dapat melihat atau mengganti fotonya.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
 values('mess-avatars','mess-avatars',false,3145728,array['image/jpeg','image/png','image/webp'])
 on conflict(id) do nothing;
drop policy if exists mess_avatar_read on storage.objects;
create policy mess_avatar_read on storage.objects for select to authenticated
 using (bucket_id='mess-avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists mess_avatar_insert on storage.objects;
create policy mess_avatar_insert on storage.objects for insert to authenticated
 with check (bucket_id='mess-avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists mess_avatar_update on storage.objects;
create policy mess_avatar_update on storage.objects for update to authenticated
 using (bucket_id='mess-avatars' and (storage.foldername(name))[1]=(select auth.uid())::text)
 with check (bucket_id='mess-avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists mess_avatar_delete on storage.objects;
create policy mess_avatar_delete on storage.objects for delete to authenticated
 using (bucket_id='mess-avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);

-- Master awal: harga 0 wajib disesuaikan dengan harga penggantian perusahaan.
insert into public.mess_assets(nama,harga,urutan)
 select v.nama,0,v.urutan from (values ('Selimut',1),('Bantal kepala',2),('Bantal guling',3),('Sarung bantal',4),('Seprai',5)) v(nama,urutan)
 where not exists(select 1 from public.mess_assets a where a.nama=v.nama);
insert into public.mess_tools(nama,urutan)
 select v.nama,v.urutan from (values ('Sapu lantai',1),('Pengki',2),('Pel',3)) v(nama,urutan)
 where not exists(select 1 from public.mess_tools a where a.nama=v.nama);

notify pgrst,'reload schema';
commit;

-- Langkah berikutnya: buat akun Auth, lalu jalankan admin_pertama.sql.
