-- Mess Karyawan V5: jalankan SEKALI setelah database V3/V4 terpasang.
-- Untuk instalasi baru: supabase_setup.sql dahulu, lalu file ini.
-- Aman dijalankan ulang. Data karyawan, kamar, dan akun tidak dihapus.
begin;

create table if not exists public.mess_repairs (
  id bigint generated by default as identity primary key,
  kamar_id bigint not null references public.mess_rooms(id) on delete cascade,
  judul text not null check (length(btrim(judul)) between 1 and 200),
  status text not null default 'belum' check (status in ('belum','diproses','selesai')),
  penanggung_jawab text,
  tgl_lapor date not null default ((now() at time zone 'Asia/Jayapura')::date),
  tgl_selesai date,
  catatan text,
  dibuat_oleh text not null,
  diubah_oleh text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mess_repair_completion check (
    (status='selesai' and tgl_selesai is not null and tgl_selesai>=tgl_lapor)
    or (status<>'selesai' and tgl_selesai is null)
  )
);
create index if not exists mess_repair_room on public.mess_repairs(kamar_id,status);
alter table public.mess_repairs enable row level security;
drop policy if exists mess_repair_read on public.mess_repairs;
create policy mess_repair_read on public.mess_repairs for select to authenticated
using ((select auth.uid()) is not null);
revoke all on public.mess_repairs from public,anon,authenticated;
grant select on public.mess_repairs to authenticated;

create or replace function public.mess_refresh_repair_condition() returns trigger
language plpgsql security definer set search_path=''
as $$
declare v_room bigint; v_damaged boolean;
begin
 v_room:=case when tg_op='DELETE' then old.kamar_id else new.kamar_id end;
 select exists(select 1 from public.mess_repairs where kamar_id=v_room and status<>'selesai') into v_damaged;
 update public.mess_rooms set rusak=v_damaged,updated_at=now()
 where id=v_room and rusak is distinct from v_damaged;
 return null;
end
$$;
drop trigger if exists mess_repair_condition on public.mess_repairs;
create trigger mess_repair_condition after insert or update or delete on public.mess_repairs
for each row execute function public.mess_refresh_repair_condition();

-- Tanda kerusakan lama dijadikan pekerjaan terbuka agar tetap terlihat.
insert into public.mess_repairs(kamar_id,judul,catatan,dibuat_oleh,diubah_oleh)
select r.id,'Kerusakan kamar',r.catatan,'Data sebelum V5','Data sebelum V5'
from public.mess_rooms r where r.rusak
and not exists(select 1 from public.mess_repairs p where p.kamar_id=r.id and p.status<>'selesai');

create or replace function public.mess_save_repair(p_id bigint,p_data jsonb) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare v_old public.mess_repairs; v_result public.mess_repairs; v_room bigint;
 v_title text; v_status text; v_pic text; v_date date; v_done date;
begin
 perform public.mess_require(1);
 if jsonb_typeof(p_data) is distinct from 'object' then raise exception 'Data perbaikan tidak valid.'; end if;
 if p_id is null then v_room:=(p_data->>'kamar_id')::bigint;
 else
   select kamar_id into v_room from public.mess_repairs where id=p_id;
   if not found then raise exception 'Perbaikan tidak ditemukan.'; end if;
 end if;
 perform 1 from public.mess_rooms where id=v_room for update;
 if not found then raise exception 'Kamar tidak ditemukan.'; end if;
 if p_id is not null then
   select * into v_old from public.mess_repairs where id=p_id for update;
   if not found then raise exception 'Perbaikan tidak ditemukan.'; end if;
   if nullif(p_data->>'expected_updated_at','') is null
     or (p_data->>'expected_updated_at')::timestamptz<>v_old.updated_at then
     raise exception 'Data perbaikan sudah berubah. Tutup formulir dan perbarui data.'; end if;
   if (p_data->>'kamar_id')::bigint is distinct from v_room then raise exception 'Kamar perbaikan tidak dapat diganti.'; end if;
 end if;
 v_title:=btrim(coalesce(p_data->>'judul',''));
 v_status:=coalesce(p_data->>'status','belum');
 v_pic:=nullif(btrim(p_data->>'penanggung_jawab'),'');
 v_date:=coalesce(nullif(p_data->>'tgl_lapor','')::date,(now() at time zone 'Asia/Jayapura')::date);
 v_done:=case when v_status='selesai' then nullif(p_data->>'tgl_selesai','')::date else null end;
 if length(v_title) not between 1 and 200 then raise exception 'Kerusakan wajib diisi, maksimal 200 karakter.'; end if;
 if v_status not in ('belum','diproses','selesai') then raise exception 'Status perbaikan tidak valid.'; end if;
 if v_status<>'belum' and v_pic is null then raise exception 'Isi penanggung jawab perbaikan.'; end if;
 if coalesce(length(v_pic),0)>200 or coalesce(length(p_data->>'catatan'),0)>4000 then raise exception 'Catatan atau penanggung jawab terlalu panjang.'; end if;
 if v_date>(now() at time zone 'Asia/Jayapura')::date then raise exception 'Tanggal laporan tidak boleh melewati hari ini.'; end if;
 if v_status='selesai' and (v_done is null or v_done<v_date or v_done>(now() at time zone 'Asia/Jayapura')::date) then
   raise exception 'Tanggal selesai wajib diisi, antara tanggal laporan dan hari ini.'; end if;
 if p_id is null then
   insert into public.mess_repairs(kamar_id,judul,status,penanggung_jawab,tgl_lapor,tgl_selesai,catatan,dibuat_oleh,diubah_oleh)
   values(v_room,v_title,v_status,v_pic,v_date,v_done,nullif(btrim(p_data->>'catatan'),''),public.mess_actor(),public.mess_actor())
   returning * into v_result;
 else
   update public.mess_repairs set judul=v_title,status=v_status,penanggung_jawab=v_pic,tgl_lapor=v_date,
     tgl_selesai=v_done,catatan=nullif(btrim(p_data->>'catatan'),''),diubah_oleh=public.mess_actor(),updated_at=now()
   where id=p_id returning * into v_result;
 end if;
 return to_jsonb(v_result);
end
$$;

-- Impor satu file dalam satu transaksi: satu baris gagal, seluruh file dibatalkan.
create or replace function public.mess_import_data(p_kind text,p_rows jsonb) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare v_item jsonb; v_data jsonb; v_saved jsonb; v_old jsonb; v_key text; v_allowed text[];
 v_new integer:=0; v_updated integer:=0; v_line integer; v_state text; v_message text;
begin
 if p_kind not in ('employees','rooms') or p_kind is null then raise exception 'Jenis impor tidak valid.'; end if;
 perform public.mess_require(case when p_kind='rooms' then 2 else 1 end);
 if jsonb_typeof(p_rows) is distinct from 'array' then raise exception 'Data impor harus berupa daftar.'; end if;
 if jsonb_array_length(p_rows) not between 1 and 1000 or octet_length(p_rows::text)>3000000 then
   raise exception 'Impor maksimal 1.000 baris dan 3 MB data.'; end if;
 v_allowed:=case when p_kind='employees' then
   array['nik','nama','gender','department','jabatan','gol','fasilitas','perusahaan','point_of_hire','tgl_masuk_kerja','tgl_masuk_mess','expected_updated_at']
   else array['lokasi_hunian','block','no_kamar','gender','jumlah_bed','floor','golongan','fasilitas','catatan','expected_updated_at'] end;
 -- Serialisasi impor menghindari dua file bersamaan saling mendahului.
 perform pg_catalog.pg_advisory_xact_lock(519305);
 for v_item in select value from jsonb_array_elements(p_rows) loop
   begin
     v_line:=coalesce((v_item->>'line')::integer,0);
     v_data:=v_item->'data'; v_old:=null; v_key:=nullif(v_item->>'existing_key','');
     if jsonb_typeof(v_data) is distinct from 'object' then raise exception 'Baris tidak valid.'; end if;
     if exists(select 1 from jsonb_object_keys(v_data) k where not k=any(v_allowed)) then raise exception 'Kolom impor tidak didukung.'; end if;
     if p_kind='employees' then
       if v_key is not null then
         select to_jsonb(e) into v_old from public.mess_employees e where e.nik=v_key for update;
         if v_old is null then raise exception 'Karyawan tidak ditemukan.'; end if;
         if v_old->>'status'<>'aktif' then raise exception 'Karyawan sudah keluar kerja. Gunakan formulir karyawan.'; end if;
       end if;
     else
       if v_key is not null then
         select to_jsonb(r) into v_old from public.mess_rooms r where r.id=v_key::bigint for update;
         if v_old is null then raise exception 'Kamar tidak ditemukan.'; end if;
       end if;
     end if;
     if v_key is not null and (nullif(v_data->>'expected_updated_at','') is null
       or (v_data->>'expected_updated_at')::timestamptz<>(v_old->>'updated_at')::timestamptz) then
       raise exception 'Data sudah berubah sejak pratinjau. Baca ulang file dan periksa kembali.'; end if;
     v_data:=coalesce(v_old,'{}'::jsonb)||v_data;
     if p_kind='employees' then
       v_data:=v_data||jsonb_build_object('status','aktif');
       v_saved:=public.mess_save_employee(v_key,v_data);
       if jsonb_typeof(v_item->'placement')='object' then
         if nullif(v_item->'placement'->>'room_id','') is null or nullif(v_item->'placement'->>'bed','') is null then raise exception 'Penempatan tidak lengkap.'; end if;
         perform public.mess_move_employee(v_saved->>'nik',(v_item->'placement'->>'room_id')::bigint,(v_item->'placement'->>'bed')::integer);
       end if;
     else
       v_saved:=public.mess_save_room(v_key::bigint,v_data);
     end if;
     if v_key is null then v_new:=v_new+1; else v_updated:=v_updated+1; end if;
   exception when others then
     get stacked diagnostics v_message=message_text,v_state=returned_sqlstate;
     raise exception using message=format('Baris %s: %s Seluruh impor dibatalkan.',v_line,v_message),errcode=v_state;
   end;
 end loop;
 return jsonb_build_object('created',v_new,'updated',v_updated);
end
$$;

revoke all on function public.mess_refresh_repair_condition(),public.mess_save_repair(bigint,jsonb),public.mess_import_data(text,jsonb) from public,anon,authenticated;
grant execute on function public.mess_save_repair(bigint,jsonb),public.mess_import_data(text,jsonb) to authenticated;

-- Fungsi kamar diperbarui di bawah agar tanda kerusakan dan daftar perbaikan konsisten.
create or replace function public.mess_save_room(p_id bigint,p_data jsonb) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare v_room public.mess_rooms; v_gender text; v_beds integer; v_loc text; v_block text; v_no text;
begin
 perform public.mess_require(case when p_id is null then 2 else 1 end);
 v_loc:=btrim(coalesce(p_data->>'lokasi_hunian',''));
 v_block:=btrim(coalesce(p_data->>'block','')); v_no:=btrim(coalesce(p_data->>'no_kamar',''));
 v_gender:=nullif(p_data->>'gender',''); v_beds:=(p_data->>'jumlah_bed')::integer;
 if v_loc='' or v_block='' or v_no='' then raise exception 'Lokasi, blok, dan nomor kamar wajib diisi.'; end if;
 if v_beds is null or v_beds<1 or v_beds>100 then raise exception 'Jumlah bed harus 1–100.'; end if;
 if p_id is not null then
   select * into v_room from public.mess_rooms where id=p_id for update;
   if not found then raise exception 'Kamar tidak ditemukan.'; end if;
   if nullif(p_data->>'expected_updated_at','') is not null
      and (p_data->>'expected_updated_at')::timestamptz <> v_room.updated_at then
     raise exception 'Data kamar sudah diubah oleh akun lain. Tutup formulir, perbarui data, lalu edit kembali.';
   end if;
   if exists(select 1 from public.mess_employees where kamar_id=p_id and no_bed>v_beds) then
     raise exception 'Jumlah bed tidak boleh lebih kecil dari nomor bed penghuni yang masih aktif.'; end if;
   if exists(select 1 from public.mess_employees where kamar_id=p_id and gender is distinct from v_gender) then
     raise exception 'Gender kamar harus sesuai dengan penghuni yang masih aktif.'; end if;
   update public.mess_rooms set lokasi_hunian=v_loc,block=v_block,no_kamar=v_no,
     floor=nullif(btrim(p_data->>'floor'),''),gender=v_gender,
     golongan=nullif(p_data->>'golongan','')::integer,
     fasilitas=nullif(p_data->>'fasilitas',''),jumlah_bed=v_beds,
     rusak=coalesce((p_data->>'rusak')::boolean,false),catatan=nullif(btrim(p_data->>'catatan'),''),
     updated_at=now() where id=p_id returning * into v_room;
 else
   insert into public.mess_rooms(lokasi_hunian,block,no_kamar,floor,gender,golongan,fasilitas,jumlah_bed,rusak,catatan)
   values(v_loc,v_block,v_no,nullif(btrim(p_data->>'floor'),''),v_gender,
     nullif(p_data->>'golongan','')::integer,nullif(p_data->>'fasilitas',''),v_beds,
     coalesce((p_data->>'rusak')::boolean,false),nullif(btrim(p_data->>'catatan'),''))
   returning * into v_room;
 end if;
 if v_room.rusak then
   if not exists(select 1 from public.mess_repairs where kamar_id=v_room.id and status<>'selesai') then
     insert into public.mess_repairs(kamar_id,judul,catatan,dibuat_oleh,diubah_oleh)
     values(v_room.id,'Kerusakan kamar',v_room.catatan,public.mess_actor(),public.mess_actor());
   end if;
 elsif exists(select 1 from public.mess_repairs where kamar_id=v_room.id and status<>'selesai') then
   raise exception 'Masih ada perbaikan terbuka. Selesaikan melalui daftar Perbaikan kamar.';
 end if;
 select * into v_room from public.mess_rooms where id=v_room.id;
 return to_jsonb(v_room);
exception when unique_violation then raise exception 'Kamar dengan lokasi, blok, dan nomor ini sudah terdaftar.';
end
$$;



commit;
