(function(g){
'use strict';const $=id=>document.getElementById(id),e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),icons=g.LinkIkon;
let A,S,rows=[],group='Camp & Facility',managing=false,editing=null,recordId='',request=0,busy=false,logoBlob=null,logoObject='',photoRequest=0;
const form=$('link-form'),dialog=$('link-dialog');
function error(id,text){$(id).textContent=text;$(id).hidden=!text;}
function icon(v){return v.logoUrl?`<img class="custom-link-logo" src="${e(v.logoUrl)}" alt="" loading="lazy">`:(icons[v.ikon]||icons.dokumen).svg;}
function openLink(v,css='mini-link'){let href;try{href=S.url(v.url);}catch{return `<span class="${css} link-unavailable">${e(v.nama)} <small>Belum tersedia</small></span>`;}return `<a class="${css}" href="${e(href)}" target="_blank" rel="noopener noreferrer"><span class="row-action-copy"><strong>${e(v.nama)}</strong>${v.keterangan?`<span>${e(v.keterangan)}</span>`:''}</span><span class="external-arrow" aria-hidden="true">↗</span></a>`;}
function groupedLinks(v,css='mini-link'){
 const groups=[...new Set(v.tombol.map(t=>t.grup||''))];return groups.map(name=>{const links=v.tombol.filter(t=>(t.grup||'')===name).map(t=>openLink(t,css)).join('');return name?`<div class="it-group"><div class="it-group-title"><span class="it-group-badge">${e(name)}</span></div><div class="it-group-actions">${links}</div></div>`:links;}).join('');
}
function priority(v){const content=`<div class="card-top"><div class="icon icon-accent">${icon(v)}</div><span class="external-arrow" aria-hidden="true">${v.tombol.length===1?'↗':'⌄'}</span></div><div class="card-copy"><strong>${e(v.nama)}</strong>${v.keterangan?`<span>${e(v.keterangan)}</span>`:''}</div>`;
 if(v.tombol.length===1)return `<a class="priority-card ${e(v.warna)}" href="${e(S.url(v.tombol[0].url))}" target="_blank" rel="noopener noreferrer">${content}</a>`;
 return `<details class="priority-card priority-group ${e(v.warna)}"><summary class="priority-summary">${content}</summary><div class="priority-links">${groupedLinks(v)}</div></details>`;
}
function ordinary(v){const content=`<div class="row-left"><div class="row-icon">${icon(v)}</div><div class="row-text"><strong>${e(v.nama)}</strong>${v.keterangan?`<span>${e(v.keterangan)}</span>`:''}</div></div>`;
 if(v.tombol.length===1)return `<a class="row ${e(v.warna)}" href="${e(S.url(v.tombol[0].url))}" target="_blank" rel="noopener noreferrer">${content}<span class="external-arrow" aria-hidden="true">↗</span></a>`;
 return `<details class="row row-group ${e(v.warna)}"><summary class="row-summary">${content}<span class="row-chevron" aria-hidden="true">⌄</span></summary><div class="row-actions">${v.tombol.map(t=>openLink(t,'row-action')).join('')}</div></details>`;
}
function external(v){return `<article class="external-card ${e(v.warna)}${v.tombol.some(t=>t.grup)?' it-helpdesk-card':''}"><div class="external-head"><div class="icon icon-accent">${icon(v)}</div><div><strong>${e(v.nama)}</strong>${v.keterangan?`<span>${e(v.keterangan)}</span>`:''}</div></div>${groupedLinks(v)}</article>`;}
function render(){
 const active=!!A?.profile,allowed=active&&A.superAdmin();$('link-manage-toggle').hidden=!allowed;if(!allowed)managing=false;$('link-current').hidden=managing;$('link-manager').hidden=!managing;
 if(!active){$('link-current').innerHTML='<p class="link-empty">Masuk ke Portal GA untuk membuka Link Kerja.</p>';$('link-manage-list').innerHTML='';return;}
 const selected=rows.filter(v=>v.kelompok===group).sort((a,b)=>a.urutan-b.urutan||a.nama.localeCompare(b.nama,'id-ID')||a.id.localeCompare(b.id));
 $('link-manage-group').textContent=group;$('link-manage-list').innerHTML=selected.length?selected.map(v=>`<article class="link-manage-row"><div class="row-icon">${icon(v)}</div><div><strong>${e(v.nama)}</strong><p>${v.aktif?'Aktif':'Nonaktif'}${v.utama?' · Link utama':''} · Urutan ${v.urutan}</p></div><button type="button" class="link-button" data-edit-link="${e(v.id)}" aria-label="Edit ${e(v.nama)}">Edit</button></article>`).join(''):'<p class="link-empty">Belum ada link '+e(group)+'.</p>';
 const visible=selected.filter(v=>v.aktif);if(!visible.length){$('link-current').innerHTML='<div class="link-empty"><p>Belum ada link '+e(group)+'.</p>'+(allowed?'<button type="button" class="link-button" data-new-link>Tambah link</button>':'')+'</div>';return;}
 if(group==='External'){$('link-current').innerHTML=`<section class="section"><div class="section-head"><div class="section-title"><h2>External</h2></div></div><div class="external-grid">${visible.map(external).join('')}</div></section>`;return;}
 const top=visible.filter(v=>v.utama),other=visible.filter(v=>!v.utama);$('link-current').innerHTML=(top.length?`<section class="section"><div class="section-head"><div class="section-title"><h2>Prioritas</h2><p>Link yang paling sering digunakan.</p></div><span class="section-meta">${top.length} link utama</span></div><div class="priority-grid">${top.map(priority).join('')}</div></section>`:'')+(other.length?`<section class="section"><div class="section-head"><div class="section-title"><h2>${e(group)} lainnya</h2></div></div><div class="list-panel">${other.map(ordinary).join('')}</div></section>`:'');
}
async function refresh(){if(!A||!S)return;const seq=++request;await A.ready;const owner=A.profile?.id;if(!owner){rows=[];render();return;}try{const data=await S.list();if(seq!==request||owner!==A.profile?.id)return;rows=data;error('link-error','');$('link-retry').hidden=true;render();}catch(err){if(seq!==request)return;error('link-error',err.message);$('link-retry').hidden=false;if(!rows.length)$('link-current').innerHTML='<p class="link-empty">Link belum dapat dimuat. Coba muat ulang.</p>';}}
function select(next){if(!['Camp & Facility','Canteen','External'].includes(next))return;group=next;document.querySelectorAll('[data-view]').forEach(b=>{const current=b.dataset.view===next;b.classList.toggle('active',current);b.setAttribute('aria-selected',String(current));b.tabIndex=current?0:-1;if(current){$('link-current').setAttribute('aria-labelledby',b.id);$('link-manager').setAttribute('aria-labelledby',b.id);}});render();}
function buttonsData(){return [...form.querySelectorAll('[data-link-button]')].map(row=>({nama:row.querySelector('[data-button-name]').value,url:row.querySelector('[data-button-url]').value,keterangan:row.querySelector('[data-button-description]').value,grup:row.querySelector('[data-button-group]').value}));}
function buttons(values){$('link-buttons').innerHTML=values.map((v,i)=>`<fieldset data-link-button><legend>Tombol ${i+1}</legend><div class="link-fields"><label>Nama tombol<input data-button-name required maxlength="100" value="${e(v.nama)}"></label><label>Alamat link<input data-button-url type="url" maxlength="3000" value="${e(v.url)}" placeholder="https://…"></label><label>Keterangan <small>opsional</small><input data-button-description maxlength="200" value="${e(v.keterangan)}"></label><label>Kelompok tombol <small>opsional</small><input data-button-group maxlength="100" value="${e(v.grup)}"></label></div><button class="link-button" type="button" data-remove-button="${i}">Hapus tombol</button></fieldset>`).join('');$('link-add-button').disabled=values.length>=12;activeFields();}
function activeFields(){form.querySelectorAll('[data-button-url]').forEach(input=>input.required=form.elements.aktif.checked);const external=$('link-group').value==='External';$('link-primary-field').hidden=external;if(external)form.elements.utama.checked=false;}
function logoPreview(){const upload=$('link-logo-mode').value==='logo';$('link-icon-field').hidden=upload;$('link-logo-field').hidden=!upload;const src=logoObject||editing?.logoUrl;$('link-logo-preview').innerHTML=upload&&src?`<img src="${e(src)}" alt="">`:(icons[$('link-icon').value]||icons.dokumen).svg;}
async function edit(id){if(!A?.superAdmin())return;editing=id?rows.find(v=>v.id===id):null;if(id&&!editing)throw new Error('Link tidak ditemukan. Muat ulang.');recordId=editing?.id||crypto.randomUUID();form.reset();if(logoObject)URL.revokeObjectURL(logoObject);logoObject='';logoBlob=null;photoRequest++;$('link-save').disabled=false;error('link-form-error','');$('link-logo-status').textContent='';
 form.elements.nama.value=editing?.nama||'';form.elements.keterangan.value=editing?.keterangan||'';form.elements.kelompok.value=editing?.kelompok||group;form.elements.urutan.value=editing?.urutan||Math.min(9999,Math.max(0,...rows.filter(v=>v.kelompok===group).map(v=>v.urutan))+1);form.elements.utama.checked=!!editing?.utama;form.elements.aktif.checked=editing?.aktif??true;
 $('link-icon').innerHTML=Object.entries(icons).map(([value,v])=>`<option value="${e(value)}">${e(v.nama)}</option>`).join('');$('link-icon').value=editing?.ikon||'dokumen';$('link-logo-mode').value=editing?.logo_path?'logo':'ikon';buttons(editing?.tombol||[{nama:'Buka link',url:'',keterangan:'',grup:''}]);logoPreview();$('link-form-title').textContent=id?'Edit link':'Tambah link';dialog.showModal();g.FormGuard?.clean(form);$('link-name').focus();}
$('link-manage-toggle').onclick=()=>{if(!A?.superAdmin())return;managing=!managing;render();};$('link-back').onclick=()=>{managing=false;render();};$('link-add').onclick=()=>edit();$('link-retry').onclick=refresh;
$('link-current').addEventListener('click',ev=>{if(ev.target.closest('[data-new-link]'))edit();});$('link-manage-list').addEventListener('click',ev=>{const b=ev.target.closest('[data-edit-link]');if(b)edit(b.dataset.editLink).catch(err=>error('link-error',err.message));});
document.querySelectorAll('[data-view]').forEach(b=>{b.onclick=()=>select(b.dataset.view);b.onkeydown=ev=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(ev.key))return;ev.preventDefault();const tabs=['Camp & Facility','Canteen','External'],i=tabs.indexOf(group),next=tabs[ev.key==='Home'?0:ev.key==='End'?2:(i+(ev.key==='ArrowRight'?1:2))%3];select(next);[...document.querySelectorAll('[data-view]')].find(t=>t.dataset.view===next).focus();};});
function close(){if(!busy)dialog.close();}for(const id of ['link-close','link-cancel'])$(id).onclick=close;dialog.addEventListener('cancel',ev=>{if(busy)ev.preventDefault();});dialog.addEventListener('close',()=>{photoRequest++;if(logoObject)URL.revokeObjectURL(logoObject);logoObject='';logoBlob=null;});
$('link-add-button').onclick=()=>{const values=buttonsData();if(values.length<12){values.push({nama:'',url:'',keterangan:'',grup:''});buttons(values);g.FormGuard?.touch(form);}};
$('link-buttons').addEventListener('click',ev=>{const b=ev.target.closest('[data-remove-button]');if(!b)return;buttons(buttonsData().filter((_,i)=>i!==Number(b.dataset.removeButton)));g.FormGuard?.touch(form);});
$('link-group').onchange=form.elements.aktif.onchange=activeFields;$('link-logo-mode').onchange=$('link-icon').onchange=logoPreview;
$('link-logo-file').onchange=async ev=>{const file=ev.target.files[0],seq=++photoRequest;if(!file)return;$('link-save').disabled=true;$('link-logo-status').textContent='Menyiapkan logo…';try{const blob=await S.prepare(file);if(seq!==photoRequest)return;if(logoObject)URL.revokeObjectURL(logoObject);logoBlob=blob;logoObject=URL.createObjectURL(blob);logoPreview();$('link-logo-status').textContent='Siap · '+Math.ceil(blob.size/1024)+' KB';}catch(err){if(seq===photoRequest){error('link-form-error',err.message);ev.target.value='';$('link-logo-status').textContent='';}}finally{if(seq===photoRequest)$('link-save').disabled=false;}};
form.onsubmit=async ev=>{ev.preventDefault();if(busy||$('link-save').disabled||!A?.superAdmin()||!form.reportValidity())return;busy=true;$('link-save').disabled=true;error('link-form-error','');try{const data={nama:form.elements.nama.value,keterangan:form.elements.keterangan.value,kelompok:form.elements.kelompok.value,urutan:Number(form.elements.urutan.value),utama:form.elements.utama.checked,aktif:form.elements.aktif.checked,ikon:form.elements.ikon.value,tombol:buttonsData()};const upload=$('link-logo-mode').value==='logo';if(upload&&!logoBlob&&!editing?.logo_path)throw new Error('Pilih gambar logo atau gunakan ikon bawaan.');await S.save(data,recordId,editing?.versi??null,{blob:upload?logoBlob:null,replaceLogo:!upload||!!logoBlob,oldPath:editing?.logo_path||''});g.FormGuard?.clean(form);busy=false;dialog.close();group=data.kelompok;select(group);await refresh();g.parent.PortalUI?.showToast('Link tersimpan.');}catch(err){error('link-form-error',err.message);}finally{busy=false;$('link-save').disabled=false;}};
async function boot(){if(g.parent===g){$('link-current').innerHTML='<p class="link-empty">Buka <a href="index.html#link-kerja">Portal GA</a> untuk masuk dan menggunakan Link Kerja.</p>';return;}if(!g.parent.Akses||!g.parent.LinkStore)await new Promise(resolve=>g.parent.addEventListener('load',resolve,{once:true}));A=g.parent.Akses;S=g.parent.LinkStore;if(!A||!S)throw new Error('Portal belum siap. Muat ulang halaman.');g.parent.document.addEventListener('akses:berubah',()=>{request++;if(!A.profile||!A.superAdmin()){g.FormGuard?.clean(form);dialog.close();}rows=[];render();refresh();});g.parent.addEventListener('hashchange',()=>{if(g.parent.location.hash==='#link-kerja')refresh();});select(group);await refresh();}
boot().catch(err=>error('link-error',err.message));
})(window);
