-- MESS KARYAWAN V8 - riwayat perubahan dan pembaruan antaradmin.
-- Database yang sudah V7: jalankan SELURUH file ini di query baru.
-- Data, akun, kamar, aturan penempatan, dan fungsi V7 tetap dipakai.
begin;

do $$
begin
 if not exists(select 1 from information_schema.columns where table_schema='public'
   and table_name='mess_rooms' and column_name='kerusakan_berat') then
   raise exception 'Jalankan update_v7.sql terlebih dahulu, lalu update_v8.sql.';
 end if;
end
$$;

create table if not exists public.mess_changes (
 id bigint generated by default as identity primary key,
 jenis text not null,
 ref text not null,
 nama text not null,
 aksi text not null check(aksi in ('tambah','ubah','hapus')),
 kolom text[] not null,
 sebelum jsonb,
 sesudah jsonb,
 oleh_id uuid,
 oleh_email text not null,
 waktu timestamptz not null default clock_timestamp()
);
create index if not exists mess_changes_time on public.mess_changes(waktu desc,id desc);
create index if not exists mess_changes_ref on public.mess_changes(jenis,ref,waktu desc);
alter table public.mess_changes enable row level security;
drop policy if exists mess_change_read on public.mess_changes;
create policy mess_change_read on public.mess_changes for select to authenticated
 using ((select public.mess_level())>=1);
revoke all on public.mess_changes from public,anon,authenticated;
revoke all on sequence public.mess_changes_id_seq from public,anon,authenticated;
grant select on public.mess_changes to authenticated;

-- Hanya kolom aplikasi yang dicatat; tidak membaca auth.users/kata sandi/token.
create or replace function public.mess_audit_snapshot(p_table text,p_row jsonb) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_keys text[]; v_result jsonb; v_label text;
begin
 if p_row is null then return null; end if;
 v_keys:=case p_table
 when 'mess_employees' then array['nik','nama','gender','department','jabatan','gol','fasilitas','perusahaan','point_of_hire','tanggal_masuk_kerja','tanggal_masuk_mess_hunian','status','kamar_id','no_bed','perlengkapan','link_bukti','tgl_resign','alasan_resign','aset_kembali','aset_snapshot','potongan']
 when 'mess_rooms' then array['id','lokasi_mess','blok','no_kamar','floor','gender','gol','fasilitas','jumlah_bed','rusak','catatan','kebersihan','keterangan_kerusakan','kerusakan_berat']
 when 'mess_profiles' then array['user_id','email','nama','role','aktif','avatar_path']
 when 'mess_assets' then array['id','nama','harga','urutan']
 when 'mess_tools' then array['id','nama','urutan']
 when 'mess_moves' then array['id','nik','tipe','dari_kamar_id','ke_kamar_id','dari_label','ke_label','dari_no_bed','ke_no_bed','diantar','diantar_oleh','diantar_pada','dibatalkan']
 else array[]::text[] end;
 select coalesce(jsonb_object_agg(key,value),'{}'::jsonb) into v_result
 from jsonb_each(p_row) where key=any(v_keys);
 if p_table='mess_employees' and nullif(p_row->>'kamar_id','') is not null then
   select lokasi_mess||' · Blok '||blok||' · Kamar '||no_kamar into v_label
   from public.mess_rooms where id=(p_row->>'kamar_id')::bigint;
   v_result:=v_result||jsonb_build_object('_kamar_label',v_label);
 end if;
 if p_table='mess_rooms' then
   v_result:=v_result||jsonb_build_object('_alat_labels',
     (select coalesce(jsonb_object_agg(id::text,nama),'{}'::jsonb) from public.mess_tools));
 end if;
 return v_result;
end
$$;

create or replace function public.mess_capture_change() returns trigger
language plpgsql security definer set search_path='' as $$
declare v_before jsonb; v_after jsonb; v_row jsonb; v_fields text[];
 v_kind text; v_ref text; v_name text;
begin
 if tg_op<>'INSERT' then v_before:=public.mess_audit_snapshot(tg_table_name,to_jsonb(old)); end if;
 if tg_op<>'DELETE' then v_after:=public.mess_audit_snapshot(tg_table_name,to_jsonb(new)); end if;
 select array_agg(k order by k) into v_fields from (
   select jsonb_object_keys(coalesce(v_before,'{}'::jsonb)) as k
   union select jsonb_object_keys(coalesce(v_after,'{}'::jsonb))
 ) fields where left(k,1)<>'_' and coalesce(v_before->k,'null'::jsonb) is distinct from coalesce(v_after->k,'null'::jsonb);
 if coalesce(cardinality(v_fields),0)=0 then return null; end if;
 v_row:=coalesce(v_after,v_before);
 v_kind:=case tg_table_name when 'mess_employees' then 'Karyawan' when 'mess_rooms' then 'Kamar'
   when 'mess_profiles' then 'Akun' when 'mess_assets' then 'Barang' when 'mess_tools' then 'Alat kebersihan'
   when 'mess_moves' then 'Pengantaran' end;
 v_ref:=case tg_table_name when 'mess_employees' then v_row->>'nik'
   when 'mess_profiles' then v_row->>'user_id' else v_row->>'id' end;
 v_name:=case when tg_table_name='mess_rooms' then
   (v_row->>'lokasi_mess')||' · Blok '||(v_row->>'blok')||' · Kamar '||(v_row->>'no_kamar')
   when tg_table_name='mess_moves' then coalesce((select nama from public.mess_employees where nik=v_row->>'nik'),v_row->>'nik')
   else coalesce(nullif(v_row->>'nama',''),v_row->>'email',v_ref) end;
 insert into public.mess_changes(jenis,ref,nama,aksi,kolom,sebelum,sesudah,oleh_id,oleh_email)
 values(v_kind,v_ref,v_name,case tg_op when 'INSERT' then 'tambah' when 'DELETE' then 'hapus' else 'ubah' end,
   v_fields,v_before,v_after,auth.uid(),coalesce(nullif(public.mess_actor(),''),'Sistem'));
 return null;
end
$$;
revoke all on function public.mess_audit_snapshot(text,jsonb),public.mess_capture_change() from public,anon,authenticated;

do $$
declare v_table text;
begin
 foreach v_table in array array['mess_employees','mess_rooms','mess_profiles','mess_assets','mess_tools','mess_moves'] loop
   execute format('drop trigger if exists mess_audit_change on public.%I',v_table);
   execute format('create trigger mess_audit_change after insert or update or delete on public.%I for each row execute function public.mess_capture_change()',v_table);
 end loop;
end
$$;

-- Publikasi yang sudah ada dan tabel lain tetap dipertahankan.
do $$
declare v_table text;
begin
 if not exists(select 1 from pg_publication where pubname='supabase_realtime') then
   create publication supabase_realtime;
 end if;
 if not exists(select 1 from pg_publication where pubname='supabase_realtime' and puballtables) then
   foreach v_table in array array['mess_employees','mess_rooms','mess_profiles','mess_assets','mess_tools','mess_moves','mess_changes','mess_deletions'] loop
     if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=v_table) then
       execute format('alter publication supabase_realtime add table public.%I',v_table);
     end if;
   end loop;
 end if;
end
$$;

create or replace function public.mess_schema_version() returns integer
language plpgsql security definer set search_path='' as $$
begin perform public.mess_require(0); return 8; end
$$;
revoke all on function public.mess_schema_version() from public,anon,authenticated;
grant execute on function public.mess_schema_version() to authenticated;
commit;
